// BERT WordPiece tokenizer — pure JS, no deps (graph task: static embeddings).
// Faithful reimplementation of the exact pipeline described by the model's
// tokenizer.json (HF `tokenizers` semantics): BertNormalizer → BertPreTokenizer
// → WordPiece. The static EmbeddingProvider (staticEmbedding.js) sums table
// rows per token id, so tokenization fidelity IS embedding fidelity — every
// rule here mirrors the Rust reference implementation, and the unit tests pin
// the output against fixtures generated by the official `tokenizers` library.
//
// Scope: BertNormalizer flags {clean_text, handle_chinese_chars, strip_accents,
// lowercase} and single-sequence encoding without special tokens.
// sentence-transformers' StaticEmbedding calls encode(add_special_tokens=False)
// (no [CLS]/[SEP]), so the post_processor in tokenizer.json is deliberately
// not applied here.

// HF is_whitespace: \t \n \r or Rust char::is_whitespace = the Unicode
// White_Space property. Beyond Zs that adds U+2028 (Zl) and U+2029 (Zp) —
// the remaining White_Space members (VT/FF/NEL) are Cc, removed by isControl
// in both implementations, so Zs + these two code points is exactly equal.
function isWhitespace(cp) {
  if (cp === 0x09 || cp === 0x0a || cp === 0x0d) return true;
  if (cp === 0x2028 || cp === 0x2029) return true;
  return /\p{Zs}/u.test(String.fromCodePoint(cp));
}

// HF is_control: the unicode_categories "Other" table = Cc/Cf/Co/Cs ONLY —
// NOT \p{C}, whose Cn (unassigned) members HF keeps in the word (they then
// UNK the whole word in WordPiece). \t \n \r are carved out as whitespace.
function isControl(cp) {
  if (cp === 0x09 || cp === 0x0a || cp === 0x0d) return false;
  return /[\p{Cc}\p{Cf}\p{Co}\p{Cs}]/u.test(String.fromCodePoint(cp));
}

// HF is_punctuation: ASCII blocks 33–47, 58–64, 91–96, 123–126 (these include
// symbols like $ + < = > ^ ` | ~ that Unicode files under S, not P) OR any
// Unicode P* category.
function isPunctuation(cp) {
  if (
    (cp >= 33 && cp <= 47) ||
    (cp >= 58 && cp <= 64) ||
    (cp >= 91 && cp <= 96) ||
    (cp >= 123 && cp <= 126)
  ) {
    return true;
  }
  return /\p{P}/u.test(String.fromCodePoint(cp));
}

// BERT's CJK ranges (BertNormalizer handle_chinese_chars) — each such char is
// wrapped in spaces so it tokenizes as its own word.
function isChineseChar(cp) {
  return (
    (cp >= 0x4e00 && cp <= 0x9fff) ||
    (cp >= 0x3400 && cp <= 0x4dbf) ||
    (cp >= 0x20000 && cp <= 0x2a6df) ||
    (cp >= 0x2a700 && cp <= 0x2b73f) ||
    (cp >= 0x2b740 && cp <= 0x2b81f) ||
    (cp >= 0x2b820 && cp <= 0x2ceaf) ||
    (cp >= 0xf900 && cp <= 0xfaff) ||
    (cp >= 0x2f800 && cp <= 0x2fa1f)
  );
}

/**
 * BertNormalizer. Flag order mirrors the Rust reference: clean_text →
 * handle_chinese_chars → strip_accents (defaulting to the lowercase flag when
 * null) → lowercase.
 */
export function bertNormalize(text, { cleanText = true, handleChineseChars = true, stripAccents = null, lowercase = true } = {}) {
  let out = '';
  for (const ch of text) {
    const cp = ch.codePointAt(0);
    if (cleanText) {
      if (cp === 0 || cp === 0xfffd || isControl(cp)) continue;
      if (isWhitespace(cp)) { out += ' '; continue; }
    }
    if (handleChineseChars && isChineseChar(cp)) { out += ` ${ch} `; continue; }
    out += ch;
  }
  const doStrip = stripAccents === null ? lowercase : stripAccents;
  if (doStrip) out = out.normalize('NFD').replace(/\p{Mn}/gu, '');
  // Per-code-point lowercase mirrors Rust char::to_lowercase: a whole-string
  // toLowerCase() would apply Unicode's context-sensitive Final_Sigma rule
  // (word-final Σ → ς), which the Rust reference never does (always Σ → σ) —
  // and the vocab distinguishes ς/σ, so the ids would diverge.
  if (lowercase) out = Array.from(out, (c) => c.toLowerCase()).join('');
  return out;
}

/** BertPreTokenizer: split on whitespace, then isolate each punctuation char. */
export function bertPreTokenize(normalized) {
  const words = [];
  let current = '';
  for (const ch of normalized) {
    const cp = ch.codePointAt(0);
    if (isWhitespace(cp)) {
      if (current) { words.push(current); current = ''; }
    } else if (isPunctuation(cp)) {
      if (current) { words.push(current); current = ''; }
      words.push(ch);
    } else {
      current += ch;
    }
  }
  if (current) words.push(current);
  return words;
}

/**
 * Build a tokenizer from a parsed tokenizer.json. Returns { encode } where
 * encode(text) → Uint32Array of token ids (no special tokens — see header).
 *
 * @param {Object} tokenizerJson parsed tokenizer.json (HF `tokenizers` format)
 */
export function createWordPieceTokenizer(tokenizerJson) {
  const model = tokenizerJson?.model;
  if (!model || model.type !== 'WordPiece') {
    throw new Error(`unsupported tokenizer model type "${model?.type}" — expected WordPiece`);
  }
  const vocab = new Map(Object.entries(model.vocab));
  const unkId = vocab.get(model.unk_token ?? '[UNK]');
  if (unkId === undefined) throw new Error('tokenizer vocab is missing the unk token');
  const prefix = model.continuing_subword_prefix ?? '##';
  const maxChars = model.max_input_chars_per_word ?? 100;

  const norm = tokenizerJson.normalizer || {};
  if (norm.type && norm.type !== 'BertNormalizer') {
    throw new Error(`unsupported normalizer "${norm.type}" — expected BertNormalizer`);
  }
  const normOpts = {
    cleanText: norm.clean_text !== false,
    handleChineseChars: norm.handle_chinese_chars !== false,
    stripAccents: norm.strip_accents ?? null,
    lowercase: norm.lowercase !== false,
  };
  const pre = tokenizerJson.pre_tokenizer || {};
  if (pre.type && pre.type !== 'BertPreTokenizer') {
    throw new Error(`unsupported pre_tokenizer "${pre.type}" — expected BertPreTokenizer`);
  }

  // Greedy longest-match-first over code points (HF counts chars, not UTF-16
  // units — Array.from splits surrogate pairs correctly).
  function wordPiece(word, out) {
    const chars = Array.from(word);
    if (chars.length > maxChars) { out.push(unkId); return; }
    const pieces = [];
    let start = 0;
    while (start < chars.length) {
      let end = chars.length;
      let id;
      while (end > start) {
        const sub = (start > 0 ? prefix : '') + chars.slice(start, end).join('');
        const found = vocab.get(sub);
        if (found !== undefined) { id = found; break; }
        end--;
      }
      if (id === undefined) { out.push(unkId); return; } // whole word → UNK
      pieces.push(id);
      start = end;
    }
    out.push(...pieces);
  }

  return {
    vocabSize: vocab.size,
    encode(text) {
      const ids = [];
      for (const word of bertPreTokenize(bertNormalize(text, normOpts))) wordPiece(word, ids);
      return Uint32Array.from(ids);
    },
  };
}

export default { createWordPieceTokenizer, bertNormalize, bertPreTokenize };
